### ISSUE TITLE
Item spawn issues on a lot of maps

### ISSUE THREAD

**Issue by CootieDwagon** [Tsuey/L4D2-Community-Update#132]
in quite a lot of official L4D2 maps, there are unreachable item spawns. either they are clipping into objects so players can't grab them while ai survivor bots can, or they spawn out of bounds, or they spawn under the map, or in some cases they spawn too close to the safe room, causing them to be deleted on map load.

there is, however, an addon made by someone who has attempted to fix these issues, but there might be more.

here is the addon https://steamcommunity.com/sharedfiles/filedetails/?id=2493132849

I've also noticed these while flying around in noclip to check for any Nav issues. would it be possible to add back in these item spawns/fix them? or would this simply break the game balance?

**Comment by Nesciuse** [comment]
I am the maker of that addon so no worries the items will be fixed :D. Because of the way item spawning works and that fixing item spawns is just fixing potential spawn positions I don't see any balance issues it could cause. The amount of spawned items won't be different just more consistent. Regarding items not spawned because of low densities which would have different amounts when fixed (not 0) if balance issue was a concern here those can be easily made coop or versus exclusive.

**Comment by CootieDwagon** [comment]
oh shit, nice! glad to hear! also I'm glad you made that addon ^w^
