### ISSUE TITLE
Hard Rain "Rainy" Common-Infected Variant Consistency

### ISSUE THREAD

**Issue by True-Boredom** [Tsuey/L4D2-Community-Update#224]
In the changelog, it says that map 3 of Hard Rain will now use the "defaultsugarmill_rain" population, which features unique "rainy" versions of the common infected that were unused.

However, the changelog doesn't say that maps 4 & 5 are going to ue the "defaultmilltown_rain" population, which means these maps won't use the "rainy" variants.

To be consistent, these three maps should all use rainy variants, or none should. (Also, my two-cents on it is that the "rainy" variants are very reflective and feel unfininished -- they use the beta models of the common infected)

**Comment by Nesciuse** [comment]
They will no worries about that

**Comment by True-Boredom** [comment]
> They will no worries about that

The problem tho is that the rainy variants look unfinished... because they are. They are very reflective, and once the novelty wears off I don't think the rainy models look as good as the normal variant.

**Comment by sergi338** [comment]
The only "unfinished" aspect about them is the color palette they're currently using, which can be easily "fixed" by replacing `ci_gradient_palette_rain.vtf` (the color gradient texture responsible for their colors in-game) with `ci_gradient_palette.vtf`. Otherwise, they're not that different from their "normal" and "swamp" counterparts (with the exception of the specular maps made from them to reflect their... "rainy" nature plus some details made with the whole "been in the rain for a while" aspect in mind such as the blood).
Model-wise, as far I've been able to tell, they're exactly the same as their normal counterparts.
 Another thing, what do you mean exactly by "very reflective"? The amount of shininess can be tweaked, but I wanna know exactly why do you think they're very reflective since well, it is pretty much the point of those guys (they're fairly "reflective" due to the fact that they have been under the rain for an unspecified amount of time, just like the swamp people are covered in.... whatever they're covered on).

**Comment by Nesciuse** [comment]
#229
