### ISSUE TITLE
Death's Door 25% Health B&W stays on after using temporary health.

### ISSUE THREAD

**Issue by Jturner2223** [Tsuey/L4D2-Community-Update#268]
It becomes more annoying than anything when it stays on forever. How the mutation did it seems like it works better.

**Comment by alexiscoutinho** [comment]
The B&W status persists by design. It reflects the current permanent health (red health), not temporary/total health. It can be cleared by healing with the ultra rare medkits or by reaching the safe room. This decision was made with balancing and realism in mind. It would look strange for the color to keep changing whenever the temporary health threshold was passed. Furthermore, the B&W status adds a lot of tension and emotion to classic finales (check out this finale https://youtu.be/EKCJMPW3Q18 for example). If the B&W status was attached to temporary/total health, it would be way too easy to stay colored, which would really nerf and defeat the purpose/novelty of this new (B&W) "feature".

**Comment by alexiscoutinho** [comment]
Although changing the B&W root/behavior might still be on the table. You are not the only one who personally prefers the more aesthetically pleasing option of hooking the color to the total health instead of the current, more realistic, approach of hooking it to the permanent health.

**Comment by Jturner2223** [comment]
> Although changing the B&W root/behavior might still be on the table. You are not the only one who personally prefers the more aesthetically pleasing option of hooking the color to the total health instead of the current, more realistic, approach of hooking it to the permanent health.

Yeah that's what I'm kinda saying, while it is a little more "realistic" it also kinda adds unnecessary tension and it's a little distracting. I feel like, imo, the B&W effect should be a warning like "oh no you're getting close to death!" and should be cleared by temporary healing items. Now I don't know if THIS is even possible, but having the effect gradually fade in whenever you're on temporary health would also be a cooler idea imo.

**Comment by Jturner2223** [comment]
Admittedly though, that video and the music were pretty epic. Still I think the effect should be alleviated when you aren't as close to death even with pills.

**Comment by alexiscoutinho** [comment]
I don't think having half B&W and half colored vision is possible. But I believe the heartbeat sound can be detached and perhaps have a different threshold to make the transition a bit more gradual.
