### ISSUE TITLE
Survivor not getting incap by hittable car (in final ?)

### ISSUE THREAD

**Issue by lunatixxx** [Tsuey/L4D2-Community-Update#279]
### Description

This is a bug that exist since very long, i always notice it on the final of The Parish. When the survivor receive a car from the tank he will sometimes not get incaped but just get up, this is not because of the effect of the adrenaline.

**Comment by lunatixxx** [comment]
Still incoherent to change an element of gameplay like that.

**Comment by lunatixxx** [comment]
And technically not true because if you take the bagage truck on final of dead air even full like you will go down.

**Comment by Derpduck** [comment]
To clarify, on gauntlet finales, which includes maps such as The Parish and Cold Stream, hittables will always deal 0.25x their normal damage and knock survivors down.
Hittables still behave as expected on holdout and scavenge finales, such as Dead Air or The Passing respectively.

This is an intentional mechanic, not a bug. While we are open to discussion on the issue, it falls out of scope for our team to change this as it is almost certainly a deliberate gameplay mechanic.
Currently there is no way to change this with the tools provided in-game, so any changes would require Valve's assistance.

Additionally, seeing as you are running a custom server with SourceMod, you can use existing plugins (`l4d2_hittable_control`) to change this behaviour.

**Comment by lunatixxx** [comment]
I set the multiplier to 1.0, it did not help.
