### ISSUE TITLE
Corpses in The Sacrifice are missing textures

### ISSUE THREAD

**Issue by True-Boredom** [Tsuey/L4D2-Community-Update#315]
### Description

There are four corpses in c7m2_barge that are missing textures.
![20221213152435_1](https://user-images.githubusercontent.com/93452872/207467043-86f4f187-e60f-45dd-b6d5-f2aa8b448fd4.jpg)

### Reproduction steps

I disabled all mods and restarted the game before I checked if the corpses were missing textures, so I'm mostly certain this isn't caused by addons or mods.

**Comment by skesssler** [comment]
those aren't missing textures, its an oversight with the infected shader. They placed ragdolls there instead of making specific dead body models. It's a long explanation but in short, it's choosing the colors that go on the eyes, mouth, and face for the whole body, so the clothes look weird. the first variant is pale so it looks very white. the red is the mouth part. To fix it they need to be replaced with models that already have the gradient lines specified. If you check the dead body vmt's you'll see tthose lines about the gradient. As a ragdoll they don't "randomize" the lines so it just chooses the top one, that is for skin.

**Comment by Tsuey** [comment]
Thank you!
